/**
 * Generates index files with exports for shadcn UI components.
 *
 * Run: pnpm run generate:exports  (or: node scripts/generate-exports.mjs)
 *
 * Configure PATHS below: each entry is a folder to scan; an index file
 * with re-exports is generated in that folder.
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// ---------------------------------------------------------------------------
// Settings (paths at top for reuse with another folder)
// ---------------------------------------------------------------------------

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

/** Path to this script relative to repo root (for header) */
const SCRIPT_PATH = path
  .relative(ROOT, fileURLToPath(import.meta.url))
  .replace(/\\/g, "/");

/**
 * List of component folders. For each folder we scan .tsx files and write
 * an index file with export * from "./name" for each.
 * - string: path relative to ROOT, index file name is "index.generated.ts"
 * - { dir, indexFile }: dir relative to ROOT, optional indexFile (default "index.generated.ts")
 */
const PATHS = [
  "packages/ui/src/components/ui",
  // "packages/other/src/components/ui",
];

// ---------------------------------------------------------------------------
// Header for the generated file
// ---------------------------------------------------------------------------

const HEADER_LINES = `/*
 * -------------------------------------------------------------------
 * 
 *  ██████╗ ███████╗███╗   ██╗███████╗██████╗  █████╗ ████████╗███████╗██████╗ 
 * ██╔════╝ ██╔════╝████╗  ██║██╔════╝██╔══██╗██╔══██╗╚══██╔══╝██╔════╝██╔══██╗
 * ██║  ███╗█████╗  ██╔██╗ ██║█████╗  ██████╔╝███████║   ██║   █████╗  ██║  ██║
 * ██║   ██║██╔══╝  ██║╚██╗██║██╔══╝  ██╔══██╗██╔══██║   ██║   ██╔══╝  ██║  ██║
 * ╚██████╔╝███████╗██║ ╚████║███████╗██║  ██║██║  ██║   ██║   ███████╗██████╔╝
 *  ╚═════╝ ╚══════╝╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═════╝ 
 * 
 * -------------------------------------------------------------------
 *
 * AUTO-GENERATED FILE. DO NOT EDIT!
 *
 * Source script: {{SOURCE_SCRIPT}}
 *
 * This file is automatically generated. Any changes will be
 * overwritten next time this file is generated.
 *
 * -------------------------------------------------------------------
 */
`;

function buildHeader() {
  return HEADER_LINES.replace("{{SOURCE_SCRIPT}}", SCRIPT_PATH);
}

// ---------------------------------------------------------------------------
// Scan directory and collect component filenames
// ---------------------------------------------------------------------------

/**
 * Returns .tsx filenames in the directory (excluding index.tsx), sorted by name.
 * index.tsx is skipped to avoid re-export cycles.
 */
function getComponentFiles(dir) {
  if (!fs.existsSync(dir)) {
    console.error("Directory not found:", dir);
    process.exit(1);
  }

  const entries = fs.readdirSync(dir, { withFileTypes: true });
  const files = entries
    .filter(
      (e) => e.isFile() && e.name.endsWith(".tsx") && e.name !== "index.tsx",
    )
    .map((e) => e.name)
    .sort((a, b) => a.localeCompare(b, undefined, { sensitivity: "base" }));

  return files;
}

/**
 * Filename without extension → export path (e.g. button → ./button).
 */
function fileToExportPath(name) {
  const base = name.replace(/\.tsx?$/, "");
  return `./${base}`;
}

// ---------------------------------------------------------------------------
// Generate index content
// ---------------------------------------------------------------------------

function generateIndexContent(componentFiles) {
  const header = buildHeader();
  const exportLines = componentFiles
    .map((file) => {
      const rel = fileToExportPath(file);
      return `export * from "${rel}";`;
    })
    .join("\n");

  return header + "\n" + exportLines + "\n";
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function normalizeEntry(entry) {
  if (typeof entry === "string") {
    return { dir: path.join(ROOT, entry), indexFile: "index.generated.ts" };
  }
  const dir = path.isAbsolute(entry.dir)
    ? entry.dir
    : path.join(ROOT, entry.dir);
  return { dir, indexFile: entry.indexFile ?? "index.generated.ts" };
}

function main() {
  const entries = PATHS.map(normalizeEntry);

  for (const { dir, indexFile } of entries) {
    const files = getComponentFiles(dir);
    const content = generateIndexContent(files);
    const outputPath = path.join(dir, indexFile);

    fs.writeFileSync(outputPath, content, "utf8");
    console.log("Generated:", outputPath);
    console.log("Exports:", files.length);
    for (const f of files) console.log("  -", f);
    if (entries.length > 1) console.log("");
  }
}

main();
